# Generated by Django 4.1.1 on 2022-10-30 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_following_users_organization_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='following_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
