# Generated by Django 4.1.3 on 2022-11-16 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_alter_organization_following_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='followed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
