# Generated by Django 4.1.1 on 2022-09-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataaccel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dataaccel',
            name='created_at',
        ),
    ]
