# Generated by Django 4.1.1 on 2022-09-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_remove_dataaccel_author_remove_dataaccel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_accels', to=settings.AUTH_USER_MODEL),
        ),
    ]
