# Generated by Django 4.1.1 on 2022-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_dataaccel_author_csvfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='csvfile',
            name='url',
            field=models.FileField(blank=True, db_column='csv_url', null=True, upload_to='csvs/'),
        ),
        migrations.AlterModelTable(
            name='csvfile',
            table='CSVFile',
        ),
    ]
