# Generated by Django 4.1.1 on 2022-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_dataaccel_author_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='file_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
