# Generated by Django 4.1.1 on 2022-10-02 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_rename_name_csvfile_file_name_alter_csvfile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file_name',
            field=models.TextField(db_column='name'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='url',
            field=models.FileField(blank=True, db_column='csv_url', null=True, upload_to='users/lex/csvs/<django.db.models.fields.TextField>'),
        ),
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together={('author', 'file_name', 'url')},
        ),
    ]
