# Generated by Django 4.1.1 on 2022-10-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_csvfile_file_name_alter_csvfile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='strUserName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='url',
            field=models.FileField(blank=True, db_column='csv_url', null=True, upload_to='users/<django.db.models.fields.related.ForeignKey>/csvs/<django.db.models.fields.TextField>'),
        ),
    ]
