# Generated by Django 4.1.1 on 2022-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_strusername_csvfile_str_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='str_user_name',
            field=models.TextField(db_column='str_user_name'),
        ),
    ]
