# Generated by Django 4.1.1 on 2022-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_csvfile_str_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='str_user_name',
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='url',
            field=models.FileField(blank=True, db_column='csv_url', null=True, upload_to='users/CHANGE_ME/csvs/<django.db.models.fields.TextField>'),
        ),
    ]
