# Generated by Django 4.0.5 on 2022-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_csvfile_str_user_name_alter_csvfile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='user_name',
            field=models.TextField(db_column='user_name', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='url',
            field=models.FileField(blank=True, db_column='csv_url', null=True, upload_to='users/<django.db.models.fields.TextField>/csvs/<django.db.models.fields.TextField>'),
        ),
    ]
