# Generated by Django 4.0.5 on 2022-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_csvfile_user_name_alter_csvfile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='url',
            field=models.FileField(blank=True, db_column='csv_url', null=True, upload_to='users/test/csvs/<django.db.models.fields.TextField>'),
        ),
    ]
