# Generated by Django 4.0.5 on 2022-10-03 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0014_alter_csvfile_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='file_path',
            field=models.TextField(db_column='file_path', default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together={('author', 'file_path')},
        ),
        migrations.AlterModelTable(
            name='csvfile',
            table=None,
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='url',
        ),
    ]
