# Generated by Django 4.0.5 on 2022-10-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_rename_created_at_csvfile_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataaccel',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
