# Generated by Django 4.1.1 on 2022-10-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_rename_created_at_dataaccel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='file_name',
            field=models.TextField(db_column='file_name', default=1),
            preserve_default=False,
        ),
    ]
