# Generated by Django 4.1.1 on 2022-10-26 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0018_csvfile_file_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together={('author', 'file_path', 'file_name')},
        ),
    ]
