# Generated by Django 4.1.4 on 2022-12-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_csvfile_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataAccel',
        ),
    ]
