# Generated by Django 4.1.4 on 2023-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_description'),
        ('data', '0023_delete_dataaccel'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='registered_organizations',
            field=models.ManyToManyField(blank=True, to='organizations.organization'),
        ),
    ]
