# Generated by Django 4.1.3 on 2022-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_csvfile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
