# Generated by Django 4.1.4 on 2023-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_description'),
        ('data', '0024_csvfile_registered_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='registered_organizations',
            field=models.ManyToManyField(blank=True, related_name='uploaded_files', to='organizations.organization'),
        ),
    ]
