# Generated by Django 4.1.6 on 2023-02-02 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_csvfile_registered_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.csvfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
