# Generated by Django 4.1.6 on 2023-02-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_tagcsvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcsvfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='data.csvfile'),
        ),
    ]
