# Generated by Django 4.1.4 on 2023-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_alter_csvfile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='is_public_orgs',
            field=models.BooleanField(default=False),
        ),
    ]
