# Generated by Django 4.1.4 on 2023-01-13 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_csvfile_registered_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_alter_review_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title', 'file')},
        ),
    ]
