# Generated by Django 4.1.4 on 2023-01-13 20:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0025_alter_csvfile_registered_organizations'),
        ('social', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'file')},
        ),
    ]
