# Generated by Django 4.1.5 on 2023-01-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_notificationreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationreview',
            old_name='Review',
            new_name='review',
        ),
    ]
