# Generated by Django 4.1.4 on 2023-01-24 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_rename_review_notificationreview_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_conversation_set', to=settings.AUTH_USER_MODEL)),
                ('other_users', models.ManyToManyField(related_name='participant_conversation_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
