# Generated by Django 4.1.4 on 2023-01-30 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0010_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='other_users',
        ),
        migrations.AddField(
            model_name='conversation',
            name='other_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participant_conversation_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
