# Generated by Django 4.1.4 on 2023-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_conversation_other_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
